### PR TITLE
GermanLangFile Updated

### PR DESCRIPTION
**Pull request by lavaground**
Thx HerrKwak

### CODE REVIEW

**Comment by HerrKwak** [comment]
erm thats wierd :P currently rewriting it again to be more "german". will pull request once finishes (i dont know how this ended up here)

**Comment by HerrKwak** [comment]
Ill add some more outlining of the rest in a bit

**Comment by HerrKwak** [comment]
sorry for not contributing to yours but i had mine already in the works when you created yours :P would be nice if you would have a look over it [My Pull Request](https://github.com/HoxHud/HoxHud-bin/pull/33)

**Comment by lavaground** [comment]
You have closed your previous submit, I couldn't contribute to it. ;)

**Pull request closed without merging**
